### ISSUE TITLE
Failed re-login attempt after timeout

### ISSUE THREAD

**Issue by jedrz** [Salamek/huawei-lte-api#9]
Hi,

Thank you very much for creating this library! I own Huawei B529 router and I use your library via home-assistant project to detect devices presence at home. However I noticed a problem after re-login attempt. It fails with 125003 error code. Here is the traceback:

```
>>> client.wlan.host_list()
Traceback (most recent call last):
  File "/home/lukasz/Programowanie-ns/huawei-lte-api/huawei_lte_api/api/User.py", line 46, in _login
    }, refresh_csfr=True)
  File "/home/lukasz/Programowanie-ns/huawei-lte-api/huawei_lte_api/Connection.py", line 112, in post
    data = self._check_response_status(self._process_response_xml(response.content))
  File "/home/lukasz/Programowanie-ns/huawei-lte-api/huawei_lte_api/Connection.py", line 64, in _check_response_status
    error_code
huawei_lte_api.exceptions.ResponseErrorException: 125003: Unknown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lukasz/Programowanie-ns/huawei-lte-api/huawei_lte_api/AuthorizedConnection.py", line 17, in wrapped
    if not args[0]._connection.enforce_authorized_connection():
  File "/home/lukasz/Programowanie-ns/huawei-lte-api/huawei_lte_api/AuthorizedConnection.py", line 53, in enforce_authorized_connection
    if self.user.login():
  File "/home/lukasz/Programowanie-ns/huawei-lte-api/huawei_lte_api/api/User.py", line 77, in login
    return self._login(PasswordTypeEnum(int(state_login['password_type'])))
  File "/home/lukasz/Programowanie-ns/huawei-lte-api/huawei_lte_api/api/User.py", line 68, in _login
    '{}: {}'.format(e.code, message), e.code)
huawei_lte_api.exceptions.ResponseErrorException: 125003: Unknown
```

Reloading the connection with `reload` and then redoing the operation works fine. Do you have any clues how it could be fixed? Does re-login work fine for your router?

**Comment by Salamek** [comment]
@jedrz Hi, sadly i dont own any Huawei LTE router right now (I had Huawei B310s-22 borrowed from client) so no way to test that for me right now... sorry.
You must hunt this bug down on your own...

**Comment by realthk** [comment]
Same here on my Huawei B525 from Home Assistant.

**Comment by Salamek** [comment]
Closed due to old age and probably fixed by #30, if this is still a issue in version 1.3 let me know and i will reopen this issue.

**Comment by Impostor-syndrome** [comment]
Hey Salamek,  first of all, thanks for a great project.  I am currently on a b525s-65a and still experiencing this issue, I have set up a script which pulls a client list,  iv tried with 2,5,10 minutes delay,  and still experience issue mentioned above.  Is there any way where I can help out troubleshooting this?

**Comment by Salamek** [comment]
@Impostor-syndrome is hack from #56 working for you ?
